dependencies:
  runtime:
    - python:3.7
    - go:1.12.10
    - ruby:2.5.0
    - java:8.232.09
    - node:10.15.1
  build:
    - python:3.7
    - go:1.12.10
    - ruby:2.5.0
    - java:8.232.09
    - node:10.15.1

build_targets:
  - name: default
    commands:
      - echo "Experimenting with an experimental repository"
      - node --version
      - java -version
      - ruby --version
      - python3 --version
      - go version

  - name: no_container
    host_only: true
    commands:
      - echo "Experimenting with an experimental repository"
      - node --version
      - java -version
      - ruby --version
      - python3 --version
      - go version

  - name: containerdeps
    container:
      image: yourbase/yb_ubuntu:16.04
    dependencies:
      containers:
        redis:
          image: redis:latest
          port_check:
            port: 6379
            timeout: 30
    environment:
      - REDIS_HOST={{ .Containers.IP "redis" }}
    commands:
      - env
      - cat env.sh
      - bash env.sh
      - node --version

  - name: fail
    tags:
      channel: stable
    commands:
      - ashdakjhkdsa

ci:
  builds:
  - name: containerdeps
    build_target: containerdeps

  - name: failing
    build_target: fail

  - name: do_it
    build_target: default
    when: branch IS NOT 'master'

  - name: hostbuild
    build_target: no_container
    when: branch IS 'master'
